FROM golang:1.14.2 as builder

WORKDIR /go/src/github.com/lucianopc/pitaya-cli

COPY . .

RUN mkdir /app
# RUN GOOS=linux GOARCH=amd64 go build -o /app/pitaya-cli ./...

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o /app/pitaya-cli ./...


FROM scratch

COPY --from=builder /app/pitaya-cli /app/pitaya-cli
WORKDIR /app

CMD ["/app/pitaya-cli"]
